nodeLinker: node-modules
enableGlobalCache: true
checksumBehavior: throw
installStatePath: .yarn/install-state.gz

logFilters:
  - code: YN0002
    level: discard
  - code: YN0086
    level: discard
  - code: YN0068
    level: discard
