checksumBehavior: throw
enableGlobalCache: true
installStatePath: .yarn/install-state.gz
nodeLinker: node-modules

packageExtensions:
  "@firebase/analytics-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/app-check-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/auth-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/firestore-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/functions-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/installations-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/messaging-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/performance-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/remote-config-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/storage-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
