name: CI

on:
  push:
    branches: [production, develop]
  pull_request:
    branches: [production, develop]
  workflow_dispatch:

jobs:
  quality:
    name: Lint / Typecheck / Test / Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn 4
        run: corepack prepare yarn@4.3.1 --activate

      - name: Install
        run: yarn install --immutable

      - name: Lint
        run: yarn lint --if-present

      - name: Typecheck
        run: yarn typecheck --if-present || true

      - name: Unit tests
        run: yarn test:ci --if-present

      - name: Cache Firebase emulators
        uses: actions/cache@v4
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators

      - name: Rules tests (Firestore emulator)
        run: yarn test:rules

      - name: Build
        run: yarn build --if-present
