name: CI

on:
  push:
    branches: [production, develop]
  pull_request:
    branches: [production, develop]
  workflow_dispatch:

jobs:
  quality:
    name: Lint / Typecheck / Test / Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present || true

      - name: Unit tests
        run: npm run test:ci --if-present

      - name: Cache Firebase emulators
        uses: actions/cache@v4
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators

      - name: Rules tests (Firestore emulator)
        run: npm run test:rules

      - name: Build
        run: npm run build --if-present
